2024-12-03 05:00:11,212 ERROR: Exception on /profile/edit [GET] [in /home/runner/Market-Harvest/.pythonlibs/lib/python3.11/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/runner/Market-Harvest/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Market-Harvest/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 920, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Market-Harvest/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 939, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Market-Harvest/.pythonlibs/lib/python3.11/site-packages/flask/app.py", line 1212, in make_response
    raise TypeError(
TypeError: The view function for 'profile.edit_profile' did not return a valid response. The function either returned None or ended without a return statement.
2024-12-03 05:02:03,800 INFO: Auth system startup [in /home/runner/Market-Harvest/app.py:70]
2024-12-03 05:02:29,042 INFO: User logged in: nadiabellamorris [in /home/runner/Market-Harvest/auth.py:101]
